### ISSUE TITLE
When adding permissions of type GroupRef, filter groups are not appended with the added group

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus-iam#103]
Permissions of type GroupRef were added to an organization and are listed when fetching permissions of that resource. However, the filter groups are not appended with the added group (/oauth2/user?filterGroups=true) and thus members of this group don't have access to that resource.

**Comment by wwajerowicz** [comment]
It was actually caused by a typo in the group name rather than bug in IAM. Closing this issue.
