### ISSUE TITLE
The root level account should have a token that doesn't expire

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-iam#42]
In order for other services to be able to perform admin operations on IAM, we need to have a root level account with a non-expiring token.

That's required, among others, to allow KG to query IAM on administrative operations as described in https://github.com/BlueBrain/nexus-kg/issues/71

**Comment by bogdanromanx** [comment]
I would argue this is a runtime configuration for iam and deployment configuration for "other" services.

**Comment by umbreak** [comment]
Integrate with Kubernetes authentication
