### ISSUE TITLE
Unify API to create new ACLs and add ACLs

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-iam#74]
From the API client side, it does not make sense to separate those two concerns, and it becomes confusing. I would suggest to just have one of the two endpoints ([create](https://bbp-nexus.epfl.ch/dev/docs/iam/api-reference/acls.html#create-a-new-acl) or [add](https://bbp-nexus.epfl.ch/dev/docs/iam/api-reference/acls.html#add-permissions-to-a-resource-acl)), but not both. 

In the end what the client wants is to add some `permissions` for some `identity(s)` to some `path`. He does not care if there are already some permissions there or if the permissions set are the first ones.

I would choose the first option [create](https://bbp-nexus.epfl.ch/dev/docs/iam/api-reference/acls.html#create-a-new-acl) as the only one and allow to use it regardless of the existance of the path or not.

Thoughts @bogdanromanx @hygt @wwajerowicz

**Comment by bogdanromanx** [comment]
I am thinking that maybe we could just use PUT for create and update and PATCH for create and partial update.
