### ISSUE TITLE
Can't PUT permissions after a DELETE

### ISSUE THREAD

**Issue by AFrancani** [BlueBrain/nexus-iam#77]
Hi team,

I believe there is a problem with how permissions are deleted. After deleting the permissions on a given address, it is then impossible to recreate permissions (though it's possible to add permissions).

Steps to reproduce:

 - Create the permissions
```
PUT /acls/some/address

{ "acl": [{
    "identity": {
        "@id": "http://localhost:8081/v0/realms/HBP/authenticated",
        "realm": "HBP",
        "@type": "AuthenticatedRef"
    },
    "permissions": ["mypermission"]
}]}

> 210 - The request has been fulfilled and resulted in a new resource being created.
```

 - Delete them
```
DELETE /acls/some/address

> 204
```

- Try to recreate them
```
PUT /acls/some/address

{ "acl": [{
    "identity": {
        "@id": "http://localhost:8081/v0/realms/HBP/authenticated",
        "realm": "HBP",
        "@type": "AuthenticatedRef"
    },
    "permissions": ["mypermission"]
}]}

> 409 - { "code": "CannotCreateExistingPermissions" }
```

I am not proficient in Scala but I believe it comes from the `next` function in [`Acls.scala`](nexus-iam/modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/acls/Acls.scala): https://github.com/BlueBrain/nexus-iam/blob/86ddb4599d60daf972f41663608c1f0c6912ae53/modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/acls/Acls.scala#L266-L276

The next state for the `PermissionCleared` event line 270 should probably be `Initial` instead of `Current(path, Map.empty)`.

This is not a big deal in terms of API usage as you can add permissions instead of redefining the entire set but I think it introduces a bug during [service startup](nexus-iam/modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala) when changing the value of the test mode:
 - when test mode is ON, a permission is added for anonymous users at the root level
https://github.com/BlueBrain/nexus-iam/blob/86ddb4599d60daf972f41663608c1f0c6912ae53/modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala#L101-L106
 - when test mode is removed in favour of admin groups, the root permissions are deleted
https://github.com/BlueBrain/nexus-iam/blob/86ddb4599d60daf972f41663608c1f0c6912ae53/modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala#L119-L123
- then permissions for the admin groups are created at the root
https://github.com/BlueBrain/nexus-iam/blob/86ddb4599d60daf972f41663608c1f0c6912ae53/modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala#L132-L134

But given the bug, this creation is not effective, removing the global permissions for admins on the acls tree.

**Comment by bogdanromanx** [comment]
Thank you for reporting this issue @AFrancani, we have noticed the same behaviour and created #74 to address it.
The reason why the state is `Current` opposed to `Initial` is because the fact that _permissions for a path existed at some point_ is somewhat different than _permissions never existed for a path_. Unifying create and update operations under a single idempotent one should fix that.

**Comment by AFrancani** [comment]
Ok, thank you for your feedback!

**Comment by umbreak** [comment]
@AFrancani now you can `append` ACLs using the PUT method are you were doing.  So appending, deleting and appending again should not trigger that error any longer.

The next task would be to add the possibility of subtract.

**Comment by AFrancani** [comment]
Thank you @umbreak !
