### ISSUE TITLE
OpenID client identity

### ISSUE THREAD

**Issue by AFrancani** [BlueBrain/nexus-iam#79]
Hi everyone, I wanted to know if you intend to handle the [client credentials grant](https://tools.ietf.org/html/rfc6749#section-4.4) to identify an OpenID client in nexus-iam?

What we want to achieve is to set the `own` permission to a service so it can handle the creation of permissions under a given tree structure for users or groups.

At the moment, this is what we get when using an access token generated with the client credentials grant:
```javscript
{
    "code": "UnexpectedAuthenticationFailure",
    "description": "Error received from downstream authentication provider",
    "cause": "Received an unexpected http response while communicating with an external service"
}
```

**Comment by bogdanromanx** [comment]
Thank you for reporting this issue @AFrancani. This is definitely something we'd like to implement to enable cli tools to interact with the service.

This would allow you to achieve your goal, but for service to service authentication we were thinking we could leverage the underlying deployment such that it's easier to manage the service tokens (without a need to reconfigure the service). If you deploy in kubernetes or openshift we'd like to have an iam integration service that hooks into their authentication and uses the service account token to perform these operations.

**Comment by umbreak** [comment]
@bogdanromanx what you are suggesting is what it is reflected on #42 , right?

**Comment by bogdanromanx** [comment]
Right.
