### ISSUE TITLE
Listing ACLs for user

### ISSUE THREAD

**Issue by ak0ska** [BlueBrain/nexus-iam#80]
Hello,

We were wondering if you are planning to implement a feature that would allow a user to query all the addresses where he has a given permission?

Thanks,
Akos

**Comment by bogdanromanx** [comment]
Thank you for reporting this issue @ak0ska. This is definitely something we'd like to implement; we need to reverse index the permissions into something like elastic search or similar.

**Comment by ak0ska** [comment]
Hello @bogdanromanx,

That is good to hear. I would be interested to try and implement such functionality myself if you are open to accepting PRs. If that is the case, do you already have some ideas or specifications on how this feature would work like?

Thanks,
Akos

**Comment by umbreak** [comment]
The feature for checking the permissions of the authenticated user across an arbitrary number of subpaths has been developed as follows:

## Request
`GET acls/{address}?maxDepth={depth}`
Retrieve the user permissions (`Authorization` HTTP header)  for any paths, starting from `{address}` until reaching paths with a maximum depth of `{depth}` (if `{depth}` = 0, it will check on any depth)
## Response
```json
{
  "@context" : "http://nexus.example.com/v0/contexts/nexus/core/iam/v0.1.0",
  "acls" : [
    {
      "identity" : {
        "@id" : "nexus.example.com/v0/anonymous",
        "@type" : "Anonymous"
      },
      "acl" : [
        {
          "permissions" : [
            "read"
          ],
          "path" : "/some/path"
        }
      ]
    },
    {
      "identity" : {
        "@id" : "http://nexus.example.com/v0/realms/realm/users/f:9d46ddd6-134e-44d6-aa74-bdf00f48dfce:dmontero",
        "@type" : "UserRef",
        "realm" : "realm",
        "sub" : "f:9d46ddd6-134e-44d6-aa74-bdf00f48dfce:dmontero"
      },
      "acl" : [
        {
          "permissions" : ["read", "write"],
          "path" : "/some/path"
        },
        {
          "permissions" : ["own", "read", "write"],
          "path" : "/some/path/example"
        }
      ]
    }
  ]
}
```

**Comment by umbreak** [comment]
This feature has been successfully implemented. The final implementation has been explained in the [documentation](https://github.com/BlueBrain/nexus-iam/blob/199582280df969da480f112efab1a202e02d3a31/docs/src/main/paradox/api-reference/acls.md).
